### PR TITLE
More EME pages translated

### PR DESCRIPTION
**Pull request by liedekef**

### CODE REVIEW

**Comment by liedekef** [comment]
This pull is based on the latest trunk of EME (I unified some fields and such)

**Comment by johnclause** [comment]
We will need to update readme, which versions of each plugin are required ...

**Comment by liedekef** [comment]
yes ... I just had a thought to make things easier: what about qtranslate-x detecting input fields with a certain class (e.g. qtranslate-x-translatable) and have the language buttons have effect on those?
And maybe a class qtranslate-x-showbutton to be able to force the language buttons to be shown.
That would eliminate all need for a custom plugin.
Just a thought ...

**Comment by johnclause** [comment]
Wow, Franky, I think this is a great idea for plugin developers, who want to integrate permanently. This would not work for a plugin, who does not wish to modify their code or author of which is not available.

You would still need to supply which pages have some translatable fields, since -x's js is only loaded on pages requested, not all pages. Also, we need to know which form a field belongs to, which can probably be automated easily enough. So, we can set a flag like `page_config['use-qtranslate-classes']` to trigger this kind of search.

The original idea was that a plugin stays clean for all other users who do not use q-x. Only users of q-x, can enter a configuration needed in q-x configuration, or use a separate plugin which pre-configures all what is needed and gets updated, when the main plugin is changed.

As I mentioned before, all this configuration can go to a simple xml-like file, which a plugin author would include with plugin distribution. The amount of time needed to keep such a file updated or to keep all 'translatable' classes in order is probably about the same. Actually, a file might be even simpler way.

I would suggest to first finish what you are doing now (I assume not much left), to make it available for people who waits, and later we can tune a new way of integration. I am currently busy with a number of other bugs/problems.

What do you think?

**Comment by liedekef** [comment]
Indeed, let's first finish what there is. I just need to go through the EME settings page now ...

**Pull request merged**
